WM.SysProductos.AppWeb/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;
using Rotativa.AspNetCore;
using System.IO;
using WM.SysProductos.BL;
using WM.SysProductos.EN;

namespace WM.SysProductos.AppWeb.Controllers
{
    public class ProductoController : Controller
    {
        readonly ProductoBL _productoBL;
        public ProductoController(ProductoBL pProductoBL)
        {
            _productoBL = pProductoBL;
        }
        // GET: ProductoController
        public async Task<ActionResult> Index( )
        {
            
            var productos = await _productoBL.ObtenerTodosAsync();
            return View(productos);
        }

        // GET: ProductoController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ProductoController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Producto pProducto)
        {
            try
            {
                var result = await _productoBL.CrearAsync(pProducto);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductoController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var producto = await _productoBL.ObtenerPorIdAsync(new Producto { Id = id });
            return View(producto);
        }

        // POST: ProductoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Producto pProducto)
        {
            try
            {
                var result = await _productoBL.ModificarAsync(pProducto);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductoController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var rol = await _productoBL.ObtenerPorIdAsync(new Producto { Id = id });
            return View(rol);
        }

        // POST: ProductoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteProducto(int id)
        {
            try
            {
                var resul = await _productoBL.EliminarAsync(new Producto { Id = id });

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        public async Task<ActionResult> ReporteProductos()
        {
            var productos = await _productoBL.ObtenerTodosAsync();
            return new ViewAsPdf("rpProductos",productos);
        }
        public async Task<JsonResult> ProductosJson()
        {
            var productos = await _productoBL.ObtenerTodosAsync();

            var productosData = productos
                .Select(p => new
                {
                    nombre = p.Nombre,
                    stock = p.CantidadDisponible
                })
                .ToList();

            return Json(productosData);
        }
        public async Task<JsonResult> ProductosJsonPrecio()
        {
            var productos = await _productoBL.ObtenerTodosAsync();

            var productosData = productos
                .Select(p => new
                {
                    fechaCreacion = p.FechaCreacion.ToString("yyyy-MM-dd"), 
                    precio = p.Precio 
                })
                .ToList();

            var groupedData = productosData
                .GroupBy(p => p.fechaCreacion)
                .Select(g => new
                {
                    fecha = g.Key,
                    precioPromedio = g.Average(p => p.precio) // Calcular el precio promedio
                })
                .OrderBy(g => g.fecha)
                .ToList();

            return Json(groupedData);
        }
        [HttpPost]
        public async Task<IActionResult> SubirExcel(IFormFile archivoExcel)
        {
            if (archivoExcel == null || archivoExcel.Length == 0)
            {
                return RedirectToAction("Index");
            }

            var productos = new List<Producto>();

            using (var stream = new MemoryStream())
            {
                await archivoExcel.CopyToAsync(stream);
                using (var package = new ExcelPackage(stream))
                {
                    var hojaExcel = package.Workbook.Worksheets[0];

                    int rowCount = hojaExcel.Dimension.Rows;

                    for (int row = 2; row <= rowCount; row++)
                    {
                        var nombre = hojaExcel.Cells[row, 1].Text;
                        var precio = hojaExcel.Cells[row, 2].GetValue<decimal>();
                        var cantidad = hojaExcel.Cells[row, 3].GetValue<int>();
                        var fecha = hojaExcel.Cells[row, 4].GetValue<DateTime>();

                        if (string.IsNullOrEmpty(nombre) || precio <= 0 || cantidad < 0)
                            continue;
                        productos.Add(new Producto
                        {
                            Nombre = nombre,
                            Precio = precio,
                            CantidadDisponible = cantidad,
                            FechaCreacion = fecha
                        });

                    }
                }
                if (productos.Count > 0)
                {
                    await _productoBL.AgregarTodosAsync(productos);
                }
                return RedirectToAction("Index");
            }
        }
        public async Task<IActionResult> ReporteProductosExcel()
        {
            var productos = await _productoBL.ObtenerTodosAsync();
            using (var package = new ExcelPackage())
            {
                var hojaExcel = package.Workbook.Worksheets.Add("Productos");

                hojaExcel.Cells["A1"].Value = "Nombre";
                hojaExcel.Cells["B1"].Value = "Precio";
                hojaExcel.Cells["C1"].Value = "Cantidad";
                hojaExcel.Cells["D1"].Value = "Fecha";

                int row = 2;
                foreach (var producto in productos)
                {
                    hojaExcel.Cells[row, 1].Value = producto.Nombre;
                    hojaExcel.Cells[row, 2].Value = producto.Precio;
                    hojaExcel.Cells[row, 3].Value = producto.CantidadDisponible;
                    hojaExcel.Cells[row, 4].Value = producto.FechaCreacion.ToString("yyyy-MM-dd");
                    row++;
                }

                hojaExcel.Cells["A:D"].AutoFitColumns();

                var stream  = new MemoryStream();
                package.SaveAs(stream);
                stream.Position = 0;
                return File(stream, "application/vnd.openxmlformarts-officedocument.spreadsheet.sheet", "ReporteProductosExcel.xlsx");
            }
        }
        
    }
}

WM.SysProductos.AppWeb/Views/Producto/Create.cshtml
@model Producto

<div class="card">
    <div class="card-header bg-primary text-white">
        <h5> Rol</h5>
    </div>
    <div class="card-body">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="mb-3">
                <label asp-for="Nombre" class="form-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Precio" class="form-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="CantidadDisponible" class="form-label"></label>
                <input asp-for="CantidadDisponible" class="form-control" />
                <span asp-validation-for="CantidadDisponible" class="text-danger"></span>
            </div>
           
            <button type="submit" class="btn btn-success"> Guardar</button>
        </form>
    </div>
</div>

WM.SysProductos.AppWeb/Views/Producto/Index.cshtml
@model List<Producto>
<div class="container mt-4">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Buscar Productos</h6>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                  
                    <div class="form-group">
                        <input type="submit" value="Buscar" class="btn btn-primary" />
                        
                                <a asp-action="ReporteProductos" class="btn btn-dark">Generar Reporte</a>
                                <a asp-action="ReporteProductosExcel" class="btn btn-dark">Generar Excel</a>
                        <a href="@Url.Action("Create", "Producto")" class="btn btn-success">Nuevo Producto</a>

                    </div>
                 
                    <div class="card card-body">
                        <form asp-controller="Producto" asp-action="SubirExcel" method="post" enctype="multipart/form-data">
                            <div class="form-group">
                                <label for="archivoExcel" class="form-label">Subir Excel</label>
                                <input type="file" name="archivoExcel" required class="form-control" />
                            </div>
                            <button type="submit" class="btn btn-primary"> Subir y guardar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div>
   

    

    
    @if (Model != null)
    {
        <table class="table table-striped table-bordered" id="tbProductos">
            <thead class="table-dark">
                <tr>
                    <td>Nmbre</td>
                    <td>Precio</td>
                    <td>Cantidad</td>
                    <td>Fecha Creacion</td>
                    <td>Acciones</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var producto in Model)
                {
                    <tr>
                        <th>@producto.Nombre</th>
                        <th>@producto.Precio</th>
                        <th>@producto.CantidadDisponible</th>
                        <th>@producto.FechaCreacion</th>

                        <th>
                            <a class="btn btn-primary" asp-contproductoler="Producto" asp-action="Edit" asp-route-id="@producto.Id">Editar</a> |
                            <a class="btn btn-danger" asp-contproductoler="Producto" asp-action="Delete" asp-route-id="@producto.Id">Eliminar</a>
                        </th>
                    </tr>
                }
            </tbody>
        </table>
    }

</div>
@section Scripts {
   
}

WM.SysProductos.AppWeb/Views/Producto/rpProductos.cshtml
@model List<Producto>
@{
    Layout = null;
}
<html>
<head>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        h1 {
            text-align: center;
            font-size: 24px;
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        table, th, td {
            border: 1px solid #000;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        .btn {
            padding: 5px 10px;
            color: white;
            text-decoration: none;
            border-radius: 5px;
        }
        .btn-primary {
            background-color: #007bff;
        }
        .btn-danger {
            background-color: #dc3545;
        }
    </style>
</head>
<body>
    <h1>Reporte de Productos</h1>
    <table>
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Precio</th>
                <th>Cantidad</th>
                <th>Fecha Creación</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var producto in Model)
            {
                <tr>
                    <td>@producto.Nombre</td>
                    <td>@producto.Precio</td>
                    <td>@producto.CantidadDisponible</td>
                    <td>@producto.FechaCreacion</td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>