WM.SysProductos.AppWeb/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;
using Rotativa.AspNetCore;
using WM.SysProductos.BL;
using WM.SysProductos.EN;

namespace WM.SysProductos.AppWeb.Controllers
{
    public class ClienteController : Controller
    {
        readonly ClienteBL _clienteBL;

        public ClienteController(ClienteBL pClienteBL)
        {
            _clienteBL = pClienteBL;
        }
        // GET: ClienteController
        public async Task<ActionResult> Index()
        {
            var clientes = await _clienteBL.ObtenerTodosAsync();
            return View(clientes);
        }

        // GET: ClienteController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ClienteController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ClienteController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Cliente pCliente)
        {
            try
            {
                var result = await _clienteBL.CrearAsync(pCliente);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ClienteController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var cliente = await _clienteBL.ObtenerPorIdAsync(new Cliente { Id = id });
            return View(cliente);
        }

        // POST: ClienteController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Cliente pCliente)
        {
            try
            {
                var result = await _clienteBL.ModificarAsync(pCliente);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ClienteController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var cliente = await _clienteBL.ObtenerPorIdAsync(new Cliente { Id = id });
            return View(cliente);
        }

        // POST: ClienteController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EliminarCliente(int id)
        {
            try
            {
                var result = await _clienteBL.EliminarAsync(new Cliente { Id = id });
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        public async Task<ActionResult> ReporteClientes()
        {
            var clientes = await _clienteBL.ObtenerTodosAsync();
            return new ViewAsPdf("rpCliente", clientes);
        }

        public async Task<IActionResult> GenerarReportePDF()
        {
            var clientes = await _clienteBL.ObtenerTodosAsync();
            return new ViewAsPdf("rpCliente", clientes)
            {
                FileName = "Reporte_Clientes.pdf",
                PageOrientation = Rotativa.AspNetCore.Options.Orientation.Landscape,
                PageSize = Rotativa.AspNetCore.Options.Size.A4,
                CustomSwitches = "--footer-center [page]"
            };
        }

        public async Task<IActionResult> ReporteClientesExcel()
        {
            var clientes = await _clienteBL.ObtenerTodosAsync();
            using (var package = new ExcelPackage())
            {
                var hojaExcel = package.Workbook.Worksheets.Add("Clientes");

                hojaExcel.Cells["A1"].Value = "Nombre";
                hojaExcel.Cells["B1"].Value = "Dirección";
                hojaExcel.Cells["C1"].Value = "Telefono";
                hojaExcel.Cells["D1"].Value = "Email";

                int row = 2;
                foreach (var cliente in clientes)
                {
                    hojaExcel.Cells[row, 1].Value = cliente.Nombre;
                    hojaExcel.Cells[row, 2].Value = cliente.Direccion;
                    hojaExcel.Cells[row, 3].Value = cliente.Telefono;
                    hojaExcel.Cells[row, 4].Value = cliente.Email;

                    row++;
                }

                hojaExcel.Cells["A:D"].AutoFitColumns();

                var stream = new MemoryStream();
                package.SaveAs(stream);
                stream.Position = 0;

                return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "ReporteClientesExcel.xlsx");
            }
        }

        [HttpPost]
        public async Task<IActionResult> SubirExcelClientes(IFormFile archivoExcel)
        {
            if (archivoExcel == null || archivoExcel.Length == 0)
            {
                return RedirectToAction("Index");
            }

            var clientes = new List<Cliente>();

            using (var stream = new MemoryStream())
            {
                await archivoExcel.CopyToAsync(stream);
                using (var package = new ExcelPackage(stream))
                {
                    var hojaExcel = package.Workbook.Worksheets[0];
                    int rowCount = hojaExcel.Dimension.Rows;

                    for (int row = 2; row <= rowCount; row++)
                    {
                        var nombre = hojaExcel.Cells[row, 1].Text;
                        var direccion = hojaExcel.Cells[row, 2].Text;
                        var telefono = hojaExcel.Cells[row, 3].Text;
                        var email = hojaExcel.Cells[row, 4].Text;

                        if (string.IsNullOrEmpty(nombre))
                            continue;

                        clientes.Add(new Cliente
                        {
                            Nombre = nombre,
                            Direccion = direccion,
                            Telefono = telefono,
                            Email = email
                        });
                    }
                }

                if (clientes.Count > 0)
                {
                    await _clienteBL.AgregarTodosAsync(clientes);
                }
                return RedirectToAction("Index");
            }
        }
    }
}

WM.SysProductos.AppWeb/Controllers/ProveedorController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WM.SysProductos.BL;
using WM.SysProductos.EN;

namespace WM.SysProductos.AppWeb.Controllers
{
    public class ProveedorController : Controller
    {
        readonly ProveedorBL _proveedorBL;
        public ProveedorController(ProveedorBL pProveedorBL)
        {
            _proveedorBL = pProveedorBL;
        }
        // GET: ProveedorController
        public async Task<ActionResult> Index()
        {
            var proveedores = await _proveedorBL.ObtenerTodosAsync();
            return View(proveedores);
        }

        // GET: ProveedorController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ProveedorController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProveedorController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Proveedor pProveedor)
        {
            try
            {
                var result = await _proveedorBL.CrearAsync(pProveedor);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProveedorController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var proveedor = await _proveedorBL.ObtenerPorIdAsync(new Proveedor { Id = id });

            return View(proveedor);
        }

        // POST: ProveedorController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Proveedor pProveedor)
        {
            try
            {
                var result = await _proveedorBL.ModificarAsync(pProveedor);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProveedorController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var proveedor = await _proveedorBL.ObtenerPorIdAsync(new Proveedor { Id = id });
            return View(proveedor);
        }

        // POST: ProveedorController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteProveedor(int id)
        {
            try
            {
                var resul = await _proveedorBL.EliminarAsync(new Proveedor { Id = id });

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WM.SysProductos.AppWeb/Views/Cliente/Create.cshtml
@model Cliente
<div class="card">
    <div class="card-header bg-primary text-white">
        <h5>Nuevo Cliente</h5>
    </div>
    <div class="card-body">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">

                <div class="mb-3">
                    <label asp-for="Nombre" class="form-label"></label>
                    <input asp-for="Nombre" class="form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="Direccion" class="form-label"></label>
                    <input asp-for="Direccion" class="form-control" />
                    <span asp-validation-for="Direccion" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="Telefono" class="form-label"></label>
                    <input asp-for="Telefono" class="form-control" />
                    <span asp-validation-for="Telefono" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="Email" class="form-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
            <button type="submit" class="btn btn-success">Guardar</button>
        </form>
    </div>
</div>

WM.SysProductos.AppWeb/Views/Cliente/Delete.cshtml
@model Cliente

<div class="card">
    <div class="card-header bg-primary text-white">
        <h5>Seguro que deseas Eliminar Cliente?</h5>
    </div>
    <div class="card-body">
        <form asp-action="EliminarCliente" method="post">
            <input asp-for="Id" class="form-control" value="@Model.Id" type="hidden" />

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">

                <div class="mb-3">
                    <label asp-for="Nombre" class="form-label"></label>
                    <input asp-for="Nombre" class="form-control" disabled />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="Direccion" class="form-label"></label>
                    <input asp-for="Direccion" class="form-control" disabled />
                    <span asp-validation-for="Direccion" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="Telefono" class="form-label"></label>
                    <input asp-for="Telefono" class="form-control" disabled />
                    <span asp-validation-for="Telefono" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="Email" class="form-label"></label>
                    <input asp-for="Email" class="form-control" disabled />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
            <button type="submit" class="btn btn-success">Eliminar</button>
        </form>
    </div>
</div>

WM.SysProductos.AppWeb/Views/Cliente/Edit.cshtml
@model Cliente

<div class="card">
    <div class="card-header bg-primary text-white">
        <h5>Editar Cliente</h5>
    </div>
    <div class="card-body">
        <form asp-action="Edit" method="post">
            <input asp-for="Id" class="form-control" value="@Model.Id" type="hidden" />

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">

                <div class="mb-3">
                    <label asp-for="Nombre" class="form-label"></label>
                    <input asp-for="Nombre" class="form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="Direccion" class="form-label"></label>
                    <input asp-for="Direccion" class="form-control" />
                    <span asp-validation-for="Direccion" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="Telefono" class="form-label"></label>
                    <input asp-for="Telefono" class="form-control" />
                    <span asp-validation-for="Telefono" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="Email" class="form-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
            <button type="submit" class="btn btn-success">Guardar</button>
        </form>
    </div>
</div>

WM.SysProductos.AppWeb/Views/Cliente/Index.cshtml
@model IEnumerable<Cliente>
<div class="container mt-4">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Clientes</h6>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">

                    <div class="form-group">

                        <a asp-controller="Cliente" asp-action="Create" class="btn btn-primary">Nuevo</a>
                        <a asp-controller="Cliente" asp-action="GenerarReportePDF" class="btn btn-success">Generar PDF</a>
                        <a asp-action="ReporteClientesExcel" class="btn btn-dark">Generar Excel</a>
                    </div>

                    <div class="card card-body" >
                        <form asp-action="SubirExcelClientes" asp-controller="Cliente" method="post" enctype="multipart/form-data">
                            <div class="form-group">
                                <label for="archivoExcel" class="form-label">Subir Excel</label>
                                <input type="file" name="archivoExcel" required class="form-control" />
                            </div>
                            <button type="submit" class="btn btn-primary">
                                <i class="fas fa-upload"></i> Subir Archivo
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div>
    

    @if (Model != null)
    {
        <table class="table table-striped table-bordered" id="tbClientes">
            <thead class="table-dark">
                <tr>
                    <td>Nombre</td>
                    <td>Direccion</td>
                    <td>Telefono</td>
                    <td>Email</td>
                    <td>Acciones</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var cliente in Model)
                {
                    <tr>
                        <th>@cliente.Nombre</th>
                        <th>@cliente.Direccion</th>
                        <th>@cliente.Telefono</th>
                        <th>@cliente.Email</th>
                        <th>
                            <a class="btn btn-primary btn-sm" asp-controller="Proveedor" asp-action="Edit" asp-route-id="@cliente.Id">
                                <i class="fas fa-edit"></i> 
                            </a>
                            |
                            <a class="btn btn-danger btn-sm" asp-controller="Proveedor" asp-action="Delete" asp-route-id="@cliente.Id">
                                <i class="fas fa-trash-alt"></i> 
                            </a>
                        </th>

                    </tr>
                }
            </tbody>
        </table>
    }
</div>

WM.SysProductos.AppWeb/Views/Cliente/rpCliente.cshtml
@model IEnumerable<Cliente>
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Reporte de Clientes</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f9f9f9;
            color: #333;
        }

        h1 {
            color: #ff6f61;
            text-align: center;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }

        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        th {
            background-color: #ffcc99;
            color: #333;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        tr:hover {
            background-color: #ffebcd;
        }

        .btn {
            padding: 8px 12px;
            text-decoration: none;
            border-radius: 4px;
            font-size: 14px;
        }

        .btn-primary {
            background-color: #ff6f61;
            color: white;
        }

        .btn-danger {
            background-color: #ffcc99;
            color: #333;
        }
    </style>
</head>
<body>
    <h1>Reporte de Clientes</h1>
    <table>
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Dirección</th>
                <th>Teléfono</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var cliente in Model)
            {
                <tr>
                    <td>@cliente.Nombre</td>
                    <td>@cliente.Direccion</td>
                    <td>@cliente.Telefono</td>
                    <td>@cliente.Email</td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>